---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ctl.orangectl.orange.db
  resources:
  - orangectls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ctl.orangectl.orange.db
  resources:
  - orangectls/finalizers
  verbs:
  - update
- apiGroups:
  - ctl.orangectl.orange.db
  resources:
  - orangectls/status
  verbs:
  - get
  - patch
  - update
