name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      KIND_CLUSTER: orangectl-test-e2e

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          go mod tidy
          go install sigs.k8s.io/kind@v0.23.0
          go install sigs.k8s.io/kustomize/kustomize/v5@latest

      - name: Build Docker images
        run: |
          docker build -t np137270/orangectl:latest .
          docker pull np137270/orange:latest 
          docker pull np137270/gateway:latest 
          docker pull curlimages/curl:latest

      - name: Run E2E Tests
        run: |
          make test-e2e
